<div class="page-header">
  <h1>View <?php echo $singularize($humanize($table)); ?></h1>
</div>
<div>
<?php foreach ($fields as $field): $column = $field['COLUMNS']['COLUMN_NAME']; ?>
    <dl>
<?php if ($relation = $findBelongsTo($column)): $referencedTable = $relation['KEY_COLUMN_USAGE']['REFERENCED_TABLE_NAME']; ?>
        <dt><?php echo ucfirst($singularize($humanize($referencedTable))); ?></dt>
<?php else: ?>
        <dt><?php echo ucfirst($humanize($column)); ?></dt>
<?php endif;?>
<?php if ($relation = $findBelongsTo($column)): $referencedTable = $relation['KEY_COLUMN_USAGE']['REFERENCED_TABLE_NAME']; ?>
        <dd><?php echo '<?php' ?> e($<?php echo $referencedTable; ?>[$data['<?php echo $table; ?>']['<?php echo $column; ?>']]);?></dd>
<?php else: ?>
        <dd><?php echo '<?php' ?> e($data['<?php echo $table; ?>']['<?php echo $column; ?>']);?></dd>
<?php endif;?>
    </dl>
<?php endforeach;?>
</div>
<p>
    <a class="btn btn-danger pull-right" href="<?php echo $path; ?>/<?php echo $table; ?>/delete/<?php echo '<?php' ?> e($id); ?>">Delete</a>
    <a class="btn btn-primary" href="<?php echo $path; ?>/<?php echo $table; ?>/edit/<?php echo '<?php' ?> e($id); ?>">Edit</a>
</p>